### ISSUE TITLE
Add meta tags

### ISSUE THREAD

**Issue by possible819** [m2-modules/nextjs-blog#44]
Add meta tags

- [x] \<meta property="og:type" content="website">
- [x] \<meta property="og:url" content="https://siteurl.com">
- [x] \<meta property="og:site_name" content="사이트 명칭">
